[project]
name = "insulin-needs-private"
version = "0.1.24" # version 1 generated in 2024 (migrated from uni) (EOL — upgrade when ready)
requires-python = ">=3.9,<3.10"
#needs brew install --cask mactex -> for some plots!
dependencies = [
    "jupyter",
    "datasets",
    "huggingface_hub>=0.30.2",
    "pyyaml",
    "numpy",
    "matplotlib",
    "seaborn",
    "pandas",
    "numba",
    "scikit-learn",
    "scipy",
    "pytest",
    "pyhamcrest",
    "plotly",
    "graphviz",
    "llvmlite",
    "tslearn",
    "wandb",
    "joblib",
    "pyarrow",
    "sequana",
    "teneto",
    "setuptools<70.0.0",
]

[tool.uv]
override-dependencies = ["kaleido; sys_platform != 'darwin' or platform_machine != 'arm64'"]