[project]
name = "insulin-needs-private"
version = "0.1.26"
requires-python = ">=3.12,<3.13"
#needs brew install --cask mactex -> for some plots!
dependencies = [
    "jupyter",
    "datasets",
    "huggingface_hub>=0.30.2",
    "pyyaml",
    "numpy",
    "matplotlib",
    "seaborn",
    "pandas>=2.2.2,<3", # staying at 2 to avoid copy on every write
    "numba",
    "scikit-learn>=1.4.2,<1.7", # for results reproducibility
    "scipy>=1.13.1,<1.14", # for results reproducibility
    "pytest",
    "pyhamcrest",
    "plotly",
    "graphviz",
    "llvmlite",
    "tslearn",
    "wandb",
    "joblib",
    "pyarrow",
    "sequana",
    "teneto",
    "setuptools<70.0.0",
]

[tool.uv]
override-dependencies = ["kaleido; sys_platform != 'darwin' or platform_machine != 'arm64'"]